// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHTNan_Lo_gm30UPeO_-AEODgmrO0dslo',
    appId: '1:1058143890645:web:355b7b0912c6b47507c65c',
    messagingSenderId: '1058143890645',
    projectId: 'task-15e41',
    authDomain: 'task-15e41.firebaseapp.com',
    storageBucket: 'task-15e41.firebasestorage.app',
    measurementId: 'G-RRCFPNB6BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC4hLDr3a5Hchvm-RQ467AMHNkH87iVT0',
    appId: '1:1058143890645:android:fa9a0c362673925107c65c',
    messagingSenderId: '1058143890645',
    projectId: 'task-15e41',
    storageBucket: 'task-15e41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCoaOk_8M7pnsfIda83Ovll_7R-wHbpeo',
    appId: '1:1058143890645:ios:b0c08cc1cb38a1df07c65c',
    messagingSenderId: '1058143890645',
    projectId: 'task-15e41',
    storageBucket: 'task-15e41.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCoaOk_8M7pnsfIda83Ovll_7R-wHbpeo',
    appId: '1:1058143890645:ios:b0c08cc1cb38a1df07c65c',
    messagingSenderId: '1058143890645',
    projectId: 'task-15e41',
    storageBucket: 'task-15e41.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );
}
